	
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS( 
	ID INT NOT NULL AUTO_INCREMENT ,
	FIRST_NAME VARCHAR(255) ,
	LAST_NAME VARCHAR(255) ,
	EMAIL VARCHAR(255), 
	PASSWORD VARCHAR(255),
	PRIMARY KEY (ID));
	
	
INSERT INTO USERS VALUES (1,'Hans','Llanos','hans.llanos@gmail.com','$2a$10$EKbPJBdp0TOdNddyo7eCceNew24o7eoPrqOt.YfJa9an17wNVaMbm');